name: CI for Web-counter

on:
  push:
    branches:
    - main

env:
  TEST: OK

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v2

    - name: See files
      run: ls -lah

  fake-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run Fake Tests
      run: |
        echo "Running fake tests..."
        sleep 10
        echo "Tests passed!"

  build-push-docker-image:
    runs-on: ubuntu-latest

    needs:
    - build-and-test
    - fake-tests

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend_webcounter:${{ github.sha }}
        file: ./frontend_webcounter.dockerfile

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend_webcounter:${{ github.sha }}
        file: ./backend_webcounter.dockerfile
