name: CI for Web-counter

on:
  push:
    branches:
    - main

env:
  TEST: OK

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v3

    steps: 
    - name: Run Fake Tests
      run: |
        echo "Running fake tests..."
        sleep 10
        echo "Tests passed!"

    build-push-docker-image:
      runs-on: ubuntu-latest

    needs:
    - build-and-test
    - Run Fake Tests

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Step 4: Build Docker images for frontend and backend
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend_webcounter:${{ github.sha }}
        file: ./frontend_webcounter.dockerfile

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend_webcounter:${{ github.sha }}
        file: ./backend_webcounter.dockerfile
